name: release

on:
  push:
    branches:
      - master

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      releaseVersion: ${{ steps.exposeVersion.outputs.releaseVersion }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Install Node dependencies
        run: npm install
      - name: Get version from package.json
        id: exposeVersion
        run: echo "::set-output name=releaseVersion::$(npm run get-version --silent)"
  prepare-release:
    needs: get-version
    runs-on: ubuntu-latest
    outputs:
      versionInfo: ${{ steps.readChangelogEntry.outputs.log_entry }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global user.email "info@arbarwings.nl"
          git config --global user.name "Melvin Oostendorp"
      - name: Create tag
        run: |
          git tag -a v${{ needs.get-version.outputs.releaseVersion }} -m ${{ needs.get-version.outputs.releaseVersion }}
          git push origin master --follow-tags
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Install Node dependencies
        run: npm install
      - name: Create CHANGELOG.md
        run: npm run create-changelog
      - name: Upload changelog as artifact
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md
  create-release:
    needs: [get-version, prepare-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download changelog for artifact
        uses: actions/download-artifact@v2
        with:
          name: changelog
      - name: Configure git
        run: |
          git config --global user.email "info@arbarwings.nl"
          git config --global user.name "Melvin Oostendorp"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Install Node dependencies
        run: npm install
      - name: Run deploy
        run: npm run deploy
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.get-version.outputs.releaseVersion }}
          release_name: ${{ needs.get-version.outputs.releaseVersion }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
      - name: Zip public folder
        run: cd public && zip -r ../website.zip . && cd ../
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./website.zip
          asset_name: website.zip
          asset_content_type: application/zip
  update-version:
    needs: [get-version, prepare-release, create-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global user.email "info@arbarwings.nl"
          git config --global user.name "Melvin Oostendorp"
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: Install Node dependencies
        run: npm install
      - name: Update version
        run: |
          npm run update-version
          git add package.json package-lock.json
          git commit -m "Update version"
          git push origin master
